# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/clion-2017.3.1/bin/cmake/bin/cmake

# The command to remove a file.
RM = /usr/bin/clion-2017.3.1/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jdecombe/Documents/Epitech/Tek2/CppModule/cpp_nanotekspice

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jdecombe/Documents/Epitech/Tek2/CppModule/cpp_nanotekspice

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/clion-2017.3.1/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/clion-2017.3.1/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jdecombe/Documents/Epitech/Tek2/CppModule/cpp_nanotekspice/CMakeFiles /home/jdecombe/Documents/Epitech/Tek2/CppModule/cpp_nanotekspice/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jdecombe/Documents/Epitech/Tek2/CppModule/cpp_nanotekspice/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cpp_nanotekspice

# Build rule for target.
cpp_nanotekspice: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpp_nanotekspice
.PHONY : cpp_nanotekspice

# fast build rule for target.
cpp_nanotekspice/fast:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/build
.PHONY : cpp_nanotekspice/fast

src/Component/Component4001.o: src/Component/Component4001.cpp.o

.PHONY : src/Component/Component4001.o

# target to build an object file
src/Component/Component4001.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/Component4001.cpp.o
.PHONY : src/Component/Component4001.cpp.o

src/Component/Component4001.i: src/Component/Component4001.cpp.i

.PHONY : src/Component/Component4001.i

# target to preprocess a source file
src/Component/Component4001.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/Component4001.cpp.i
.PHONY : src/Component/Component4001.cpp.i

src/Component/Component4001.s: src/Component/Component4001.cpp.s

.PHONY : src/Component/Component4001.s

# target to generate assembly for a file
src/Component/Component4001.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/Component4001.cpp.s
.PHONY : src/Component/Component4001.cpp.s

src/Component/Component4011.o: src/Component/Component4011.cpp.o

.PHONY : src/Component/Component4011.o

# target to build an object file
src/Component/Component4011.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/Component4011.cpp.o
.PHONY : src/Component/Component4011.cpp.o

src/Component/Component4011.i: src/Component/Component4011.cpp.i

.PHONY : src/Component/Component4011.i

# target to preprocess a source file
src/Component/Component4011.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/Component4011.cpp.i
.PHONY : src/Component/Component4011.cpp.i

src/Component/Component4011.s: src/Component/Component4011.cpp.s

.PHONY : src/Component/Component4011.s

# target to generate assembly for a file
src/Component/Component4011.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/Component4011.cpp.s
.PHONY : src/Component/Component4011.cpp.s

src/Component/Component4030.o: src/Component/Component4030.cpp.o

.PHONY : src/Component/Component4030.o

# target to build an object file
src/Component/Component4030.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/Component4030.cpp.o
.PHONY : src/Component/Component4030.cpp.o

src/Component/Component4030.i: src/Component/Component4030.cpp.i

.PHONY : src/Component/Component4030.i

# target to preprocess a source file
src/Component/Component4030.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/Component4030.cpp.i
.PHONY : src/Component/Component4030.cpp.i

src/Component/Component4030.s: src/Component/Component4030.cpp.s

.PHONY : src/Component/Component4030.s

# target to generate assembly for a file
src/Component/Component4030.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/Component4030.cpp.s
.PHONY : src/Component/Component4030.cpp.s

src/Component/Component4069.o: src/Component/Component4069.cpp.o

.PHONY : src/Component/Component4069.o

# target to build an object file
src/Component/Component4069.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/Component4069.cpp.o
.PHONY : src/Component/Component4069.cpp.o

src/Component/Component4069.i: src/Component/Component4069.cpp.i

.PHONY : src/Component/Component4069.i

# target to preprocess a source file
src/Component/Component4069.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/Component4069.cpp.i
.PHONY : src/Component/Component4069.cpp.i

src/Component/Component4069.s: src/Component/Component4069.cpp.s

.PHONY : src/Component/Component4069.s

# target to generate assembly for a file
src/Component/Component4069.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/Component4069.cpp.s
.PHONY : src/Component/Component4069.cpp.s

src/Component/Component4071.o: src/Component/Component4071.cpp.o

.PHONY : src/Component/Component4071.o

# target to build an object file
src/Component/Component4071.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/Component4071.cpp.o
.PHONY : src/Component/Component4071.cpp.o

src/Component/Component4071.i: src/Component/Component4071.cpp.i

.PHONY : src/Component/Component4071.i

# target to preprocess a source file
src/Component/Component4071.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/Component4071.cpp.i
.PHONY : src/Component/Component4071.cpp.i

src/Component/Component4071.s: src/Component/Component4071.cpp.s

.PHONY : src/Component/Component4071.s

# target to generate assembly for a file
src/Component/Component4071.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/Component4071.cpp.s
.PHONY : src/Component/Component4071.cpp.s

src/Component/Component4081.o: src/Component/Component4081.cpp.o

.PHONY : src/Component/Component4081.o

# target to build an object file
src/Component/Component4081.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/Component4081.cpp.o
.PHONY : src/Component/Component4081.cpp.o

src/Component/Component4081.i: src/Component/Component4081.cpp.i

.PHONY : src/Component/Component4081.i

# target to preprocess a source file
src/Component/Component4081.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/Component4081.cpp.i
.PHONY : src/Component/Component4081.cpp.i

src/Component/Component4081.s: src/Component/Component4081.cpp.s

.PHONY : src/Component/Component4081.s

# target to generate assembly for a file
src/Component/Component4081.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/Component4081.cpp.s
.PHONY : src/Component/Component4081.cpp.s

src/Component/ComponentInput.o: src/Component/ComponentInput.cpp.o

.PHONY : src/Component/ComponentInput.o

# target to build an object file
src/Component/ComponentInput.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/ComponentInput.cpp.o
.PHONY : src/Component/ComponentInput.cpp.o

src/Component/ComponentInput.i: src/Component/ComponentInput.cpp.i

.PHONY : src/Component/ComponentInput.i

# target to preprocess a source file
src/Component/ComponentInput.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/ComponentInput.cpp.i
.PHONY : src/Component/ComponentInput.cpp.i

src/Component/ComponentInput.s: src/Component/ComponentInput.cpp.s

.PHONY : src/Component/ComponentInput.s

# target to generate assembly for a file
src/Component/ComponentInput.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/ComponentInput.cpp.s
.PHONY : src/Component/ComponentInput.cpp.s

src/Component/ComponentOutput.o: src/Component/ComponentOutput.cpp.o

.PHONY : src/Component/ComponentOutput.o

# target to build an object file
src/Component/ComponentOutput.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/ComponentOutput.cpp.o
.PHONY : src/Component/ComponentOutput.cpp.o

src/Component/ComponentOutput.i: src/Component/ComponentOutput.cpp.i

.PHONY : src/Component/ComponentOutput.i

# target to preprocess a source file
src/Component/ComponentOutput.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/ComponentOutput.cpp.i
.PHONY : src/Component/ComponentOutput.cpp.i

src/Component/ComponentOutput.s: src/Component/ComponentOutput.cpp.s

.PHONY : src/Component/ComponentOutput.s

# target to generate assembly for a file
src/Component/ComponentOutput.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/ComponentOutput.cpp.s
.PHONY : src/Component/ComponentOutput.cpp.s

src/Component/DefaultComponent.o: src/Component/DefaultComponent.cpp.o

.PHONY : src/Component/DefaultComponent.o

# target to build an object file
src/Component/DefaultComponent.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/DefaultComponent.cpp.o
.PHONY : src/Component/DefaultComponent.cpp.o

src/Component/DefaultComponent.i: src/Component/DefaultComponent.cpp.i

.PHONY : src/Component/DefaultComponent.i

# target to preprocess a source file
src/Component/DefaultComponent.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/DefaultComponent.cpp.i
.PHONY : src/Component/DefaultComponent.cpp.i

src/Component/DefaultComponent.s: src/Component/DefaultComponent.cpp.s

.PHONY : src/Component/DefaultComponent.s

# target to generate assembly for a file
src/Component/DefaultComponent.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Component/DefaultComponent.cpp.s
.PHONY : src/Component/DefaultComponent.cpp.s

src/Gates.o: src/Gates.cpp.o

.PHONY : src/Gates.o

# target to build an object file
src/Gates.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Gates.cpp.o
.PHONY : src/Gates.cpp.o

src/Gates.i: src/Gates.cpp.i

.PHONY : src/Gates.i

# target to preprocess a source file
src/Gates.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Gates.cpp.i
.PHONY : src/Gates.cpp.i

src/Gates.s: src/Gates.cpp.s

.PHONY : src/Gates.s

# target to generate assembly for a file
src/Gates.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/Gates.cpp.s
.PHONY : src/Gates.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parsing/Parser.o: src/parsing/Parser.cpp.o

.PHONY : src/parsing/Parser.o

# target to build an object file
src/parsing/Parser.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/parsing/Parser.cpp.o
.PHONY : src/parsing/Parser.cpp.o

src/parsing/Parser.i: src/parsing/Parser.cpp.i

.PHONY : src/parsing/Parser.i

# target to preprocess a source file
src/parsing/Parser.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/parsing/Parser.cpp.i
.PHONY : src/parsing/Parser.cpp.i

src/parsing/Parser.s: src/parsing/Parser.cpp.s

.PHONY : src/parsing/Parser.s

# target to generate assembly for a file
src/parsing/Parser.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_nanotekspice.dir/build.make CMakeFiles/cpp_nanotekspice.dir/src/parsing/Parser.cpp.s
.PHONY : src/parsing/Parser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... cpp_nanotekspice"
	@echo "... src/Component/Component4001.o"
	@echo "... src/Component/Component4001.i"
	@echo "... src/Component/Component4001.s"
	@echo "... src/Component/Component4011.o"
	@echo "... src/Component/Component4011.i"
	@echo "... src/Component/Component4011.s"
	@echo "... src/Component/Component4030.o"
	@echo "... src/Component/Component4030.i"
	@echo "... src/Component/Component4030.s"
	@echo "... src/Component/Component4069.o"
	@echo "... src/Component/Component4069.i"
	@echo "... src/Component/Component4069.s"
	@echo "... src/Component/Component4071.o"
	@echo "... src/Component/Component4071.i"
	@echo "... src/Component/Component4071.s"
	@echo "... src/Component/Component4081.o"
	@echo "... src/Component/Component4081.i"
	@echo "... src/Component/Component4081.s"
	@echo "... src/Component/ComponentInput.o"
	@echo "... src/Component/ComponentInput.i"
	@echo "... src/Component/ComponentInput.s"
	@echo "... src/Component/ComponentOutput.o"
	@echo "... src/Component/ComponentOutput.i"
	@echo "... src/Component/ComponentOutput.s"
	@echo "... src/Component/DefaultComponent.o"
	@echo "... src/Component/DefaultComponent.i"
	@echo "... src/Component/DefaultComponent.s"
	@echo "... src/Gates.o"
	@echo "... src/Gates.i"
	@echo "... src/Gates.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parsing/Parser.o"
	@echo "... src/parsing/Parser.i"
	@echo "... src/parsing/Parser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

